server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduationproject?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8
    username: root
    password: yry2137
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/xmut/project/entity

